import {
    Smile,
    Coffee,
    Heart,
    Zap,
    CloudRain,
    BookOpen,
    Globe,
    Disc
} from 'lucide-react';

export const MUSIC_TRIVIA = [
    { type: "HISTORY", text: "The first ever Grammy Award for Best Rap Performance went to DJ Jazzy Jeff & The Fresh Prince." },
    { type: "FACT", text: "The world's largest functioning violin is over 13 feet tall." },
    { type: "PSYCHOLOGY", text: "Listening to music releases dopamine, the same chemical released during eating." },
    { type: "BIOLOGY", text: "Your heartbeat changes and mimics the music you listen to." },
    { type: "TIP", text: "Use 'subtractive EQ'—cutting bad frequencies is often better than boosting good ones." },
    { type: "HISTORY", text: "The CD was designed to be 74 minutes long to fit Beethoven's Ninth Symphony." },
    { type: "FACT", text: "Leo Fender, inventor of the Stratocaster, never learned how to play guitar." },
    { type: "PSYCHOLOGY", text: "Music can help severely brain-injured patients recall personal memories." },
    { type: "BIOLOGY", text: "Singing daily for ten minutes reduces stress and clears sinuses." },
    { type: "TIP", text: "High-pass filter everything except kick and bass to clean up 'mud' in a mix." },
    { type: "HISTORY", text: "The first music video played on MTV was 'Video Killed the Radio Star'." },
    { type: "FACT", text: "Termites eat wood twice as fast when listening to heavy metal." },
    { type: "PSYCHOLOGY", text: "Ambient noise at 70 dB enhances performance on creative tasks." },
    { type: "BIOLOGY", text: "Loud music can cause your lung to collapse due to intense vibrations." },
    { type: "TIP", text: "Double-track vocals to create a natural chorus effect used in pop music." },
    { type: "HISTORY", text: "Mozart sold more CDs in 2016 than Beyoncé." },
    { type: "FACT", text: "The Beatles couldn't read sheet music." },
    { type: "PSYCHOLOGY", text: "Earworms are more likely to occur when the brain is in an idle state." },
    { type: "BIOLOGY", text: "Musical training is the only activity that engages almost every area of the brain." },
    { type: "TIP", text: "Listen to your mix at low volume; if the vocals disappear, they are too quiet." },
    { type: "HISTORY", text: "The phonograph was invented by Thomas Edison in 1877." },
    { type: "FACT", text: "A piano has 230 strings and exerts 20 tons of tension." },
    { type: "PSYCHOLOGY", text: "Minor keys are perceived as sad because they mimic the pitch of a human cry." },
    { type: "BIOLOGY", text: "The cilia in your ears never regrow once damaged by loud sound." },
    { type: "TIP", text: "Use sidechain compression to duck the bass when the kick drum hits." },
    { type: "HISTORY", text: "The first song performed in space was 'Jingle Bells' on a harmonica." },
    { type: "FACT", text: "Prince played 27 instruments on his debut album." },
    { type: "PSYCHOLOGY", text: "Music can reduce chronic pain and depression by up to 21%." },
    { type: "BIOLOGY", text: "The 'middle ear' is home to the smallest bone in the human body." },
    { type: "TIP", text: "Record in a closet full of clothes to get a professional 'dead' vocal sound." },
    { type: "HISTORY", text: "The 'Amen Break' is a 6-second drum solo that founded Hip Hop and Jungle." },
    { type: "FACT", text: "Metallica is the only band to play on all 7 continents." },
    { type: "PSYCHOLOGY", text: "The 'Mozart Effect' theory suggests music briefly enhances spatial reasoning." },
    { type: "BIOLOGY", text: "Playing wind instruments can strengthen the airway to treat sleep apnea." },
    { type: "TIP", text: "Add subtle saturation to bass to make it audible on phone speakers." },
    { type: "HISTORY", text: "Queen's 'Bohemian Rhapsody' stays in B-flat major for most of its duration." },
    { type: "FACT", text: "The most expensive instrument is a Stradivarius violin sold for $15.9 million." },
    { type: "PSYCHOLOGY", text: "Music with a tempo of 60 bpm can synchronize brainwaves into alpha states." },
    { type: "BIOLOGY", text: "Loud sounds above 85 decibels cause permanent damage to ear hair cells." },
    { type: "TIP", text: "Pan instruments slightly left or right to create a wider stereo image." },
    { type: "HISTORY", text: "The first digital recording was made in 1971 by NHK in Japan." },
    { type: "FACT", text: "Eminem wrote 'The Real Slim Shady' hours before the album was due." },
    { type: "PSYCHOLOGY", text: "Musical chills are more common in people high in 'Openness to Experience'." },
    { type: "BIOLOGY", text: "The speed of sound travels 4 times faster in water than in air." },
    { type: "TIP", text: "Parallel compression keeps dynamic range while adding punch to drums." },
    { type: "HISTORY", text: "The world's oldest instrument is a 40,000-year-old vulture bone flute." },
    { type: "FACT", text: "The average lifespan of a pop star is 25 years shorter than the average person." },
    { type: "PSYCHOLOGY", text: "The 'Ithaca Effect' makes people enjoy music more if it sounds hard to play." },
    { type: "BIOLOGY", text: "Rhythm is processed in the cerebellum, which also coordinates movement." },
    { type: "TIP", text: "Use a reference track to reset your ears during long mixing sessions." },
    { type: "HISTORY", text: "The first gold record was Perry Como's 'Catch a Falling Star' in 1958." },
    { type: "FACT", text: "A standard violin is made from over 70 different pieces of wood." },
    { type: "PSYCHOLOGY", text: "Background music can decrease performance on tasks involving reading." },
    { type: "BIOLOGY", text: "Your motor cortex activates even when just listening to music without moving." },
    { type: "TIP", text: "Apply a tiny bit of reverb to the snare to give the kit depth." },
    { type: "HISTORY", text: "Elvis Presley never wrote any of his own songs." },
    { type: "FACT", text: "The 'silent' part of a CD is actually microscopic pits and lands." },
    { type: "PSYCHOLOGY", text: "Familiar music can reduce pre-surgery anxiety better than sedatives." },
    { type: "BIOLOGY", text: "Cows produce more milk when listening to relaxing music like R.E.M." },
    { type: "TIP", text: "Point the microphone at the 12th fret for the best acoustic guitar tone." },
    { type: "HISTORY", text: "The Rolling Stones' 'Satisfaction' riff came to Keith Richards in a dream." },
    { type: "FACT", text: "The shortest song ever recorded is 1.3 seconds long by Napalm Death." },
    { type: "PSYCHOLOGY", text: "Listening to happy music helps generate 'divergent' creative ideas." },
    { type: "BIOLOGY", text: "Your brain can recognize a song in as little as 100 milliseconds." },
    { type: "TIP", text: "Use 'Automated Gain' instead of heavy compression for natural vocals." },
    { type: "HISTORY", text: "The Wu-Tang Clan sold a single-copy album for $2 million." },
    { type: "FACT", text: "The Fender Telecaster was the first mass-produced solid-body guitar." },
    { type: "PSYCHOLOGY", text: "Heavy metal fans are often more gentle than the general population." },
    { type: "BIOLOGY", text: "The 'Stapedius' is the smallest muscle in the body and protects the ear." },
    { type: "TIP", text: "Check your mix in mono to ensure there is no phase cancellation." },
    { type: "HISTORY", text: "MTV was originally going to be called 'The Music Channel'." },
    { type: "FACT", text: "The space between guitar frets follows the 'Rule of 18'." },
    { type: "PSYCHOLOGY", text: "Music training before age 7 improves the brain's corpus callosum." },
    { type: "BIOLOGY", text: "Dancing releases endorphins, the body's natural painkillers." },
    { type: "TIP", text: "To make a vocal pop, try a narrow boost around 3kHz to 5kHz." },
    { type: "HISTORY", text: "The Roland TR-808 drum machine was a commercial failure at launch." },
    { type: "FACT", text: "The bridge of a violin is held by tension, not glue." },
    { type: "PSYCHOLOGY", text: "The 'Earworm' is scientifically known as 'Involuntary Musical Imagery'." },
    { type: "BIOLOGY", text: "Hearing is the only sense that remains active while you sleep." },
    { type: "TIP", text: "To get a 'lo-fi' sound, use a band-pass filter to cut highs and lows." },
    { type: "HISTORY", text: "Pink Floyd's 'Dark Side of the Moon' stayed on charts for 741 weeks." },
    { type: "FACT", text: "The G-string is the hardest guitar string to keep in tune." },
    { type: "PSYCHOLOGY", text: "Music can help people with Parkinson's improve their walking speed." },
    { type: "BIOLOGY", text: "Synchronized heartbeats occur in choir members singing together." },
    { type: "TIP", text: "Shorten the decay on your kick drum to make the rhythm feel tighter." },
    { type: "HISTORY", text: "The first song synchronized to film was in 'The Jazz Singer' in 1927." },
    { type: "FACT", text: "A grand piano's strings exert 30 tons of pressure on the frame." },
    { type: "PSYCHOLOGY", text: "Music with lyrics interferes with tasks requiring language processing." },
    { type: "BIOLOGY", text: "The fluid in your inner ear is responsible for your sense of balance." },
    { type: "TIP", text: "Use a De-esser to tame harsh 'S' and 'T' sounds in vocals." },
    { type: "HISTORY", text: "Jimi Hendrix was the highest-paid performer at Woodstock." },
    { type: "FACT", text: "The total length of grooves on one side of an LP is about 1,500 feet." },
    { type: "PSYCHOLOGY", text: "People prefer original versions of songs due to 'Status Quo Bias'." },
    { type: "BIOLOGY", text: "The human voice is produced by the larynx, or voice box." },
    { type: "TIP", text: "Layer a synth with a real instrument for an 'organic' digital sound." },
    { type: "HISTORY", text: "The 45 RPM record was introduced by RCA Victor in 1949." },
    { type: "FACT", text: "Violin bows are typically made from horsehair." },
    { type: "PSYCHOLOGY", text: "Songs with 50-80 BPM can help induce a meditative state." },
    { type: "BIOLOGY", text: "The cochlea converts sound waves into nerve signals for the brain." },
    { type: "TIP", text: "If a mix sounds muddy, look for a buildup around 250Hz." },
    { type: "HISTORY", text: "The first CD ever pressed in the USA was Bruce Springsteen’s 'Born in the U.S.A.' in 1984." },
    { type: "FACT", text: "A 'Leitmotif' is a recurring musical theme associated with a particular person, place, or idea." },
    { type: "PSYCHOLOGY", text: "Listening to music while performing repetitive tasks can increase efficiency and accuracy." },
    { type: "BIOLOGY", text: "The human ear is most sensitive to the frequency range of 2,000 to 5,000 Hz." },
    { type: "TIP", text: "To give a bass guitar more 'growl,' add a small boost around 800Hz to 1kHz." },
    { type: "HISTORY", text: "The first jazz concert ever held at Carnegie Hall was by Benny Goodman in 1938." },
    { type: "FACT", text: "The strings on a grand piano exert a combined tension of about 40,000 pounds." },
    { type: "PSYCHOLOGY", text: "The 'Reminiscence Bump' explains why we have the strongest emotional ties to music from our youth." },
    { type: "BIOLOGY", text: "Endorphins released by singing can act as a natural anesthetic for physical pain." },
    { type: "TIP", text: "When mixing, use a 'High Shelf' boost on vocals to add air and expensive-sounding clarity." },
    { type: "HISTORY", text: "In 1952, John Cage premiered '4′33″', a piece consisting of four minutes and 33 seconds of silence." },
    { type: "FACT", text: "The term 'Staccato' indicates that notes should be played in a detached, separated manner." },
    { type: "PSYCHOLOGY", text: "Musical training is linked to improved verbal memory and second-language acquisition." },
    { type: "BIOLOGY", text: "The vestibular system in the ear is what allows humans to maintain their balance while dancing." },
    { type: "TIP", text: "Avoid over-compressing your master bus; it can kill the 'life' and punch of the transients." },
    { type: "HISTORY", text: "The electric bass guitar was first commercialized by Leo Fender in 1951 (the Precision Bass)." },
    { type: "FACT", text: "A standard guitar has 6 strings, but 7, 8, and even 12-string versions are common." },
    { type: "PSYCHOLOGY", text: "The 'Halo Effect' can cause listeners to perceive a physically attractive artist's music as better." },
    { type: "BIOLOGY", text: "Rhythmic auditory stimulation can help stroke victims regain their ability to walk." },
    { type: "TIP", text: "Use a pop filter to prevent 'plosive' sounds (like P and B) from overloading the microphone." },
    { type: "HISTORY", text: "The first synthesized sound was created in 1896 using the 'Telharmonium'." },
    { type: "FACT", text: "The 'Standard Pitch' of A=440Hz was only officially adopted internationally in 1955." },
    { type: "PSYCHOLOGY", text: "Music can lower the heart rate of newborn babies in neonatal intensive care units." },
    { type: "BIOLOGY", text: "Tinnitus often occurs due to the brain trying to 'fill in' missing frequencies from hearing loss." },
    { type: "TIP", text: "Layer two different kick drum samples—one for the 'thump' and one for the 'click'." },
    { type: "HISTORY", text: "The 1980s 'Walkman' was the first device to make high-quality music truly portable." },
    { type: "FACT", text: "The most recorded song in history is 'Yesterday' by The Beatles, with over 2,200 cover versions." },
    { type: "PSYCHOLOGY", text: "Background music in grocery stores is often slow to encourage shoppers to take their time." },
    { type: "BIOLOGY", text: "Dopamine levels in the brain can spike up to 9% when listening to a musical 'climax'." },
    { type: "TIP", text: "Use 'Clip Gain' to level out a vocal performance before it even hits your compressor." },
    { type: "HISTORY", text: "The first music video to be banned by MTV was 'State of Shock' by The Jacksons." },
    { type: "FACT", text: "The bridge of a violin is typically made from maple wood." },
    { type: "PSYCHOLOGY", text: "Classical music is often used in public spaces to deter loitering and vandalism." },
    { type: "BIOLOGY", text: "Hearing is the fastest human sense; the brain can process sound 10x faster than sight." },
    { type: "TIP", text: "To make a synth lead feel 'wider,' use a chorus effect or a very short stereo delay." },
    { type: "HISTORY", text: "The first ever 'boy band' is often considered to be The Ink Spots in the 1930s." },
    { type: "FACT", text: "A 'Crescendo' is a gradual increase in the volume of a piece of music." },
    { type: "PSYCHOLOGY", text: "The 'Isoprinciple' involves matching music to a patient's current mood to gradually shift it." },
    { type: "BIOLOGY", text: "The human eardrum is only about 10 millimeters wide." },
    { type: "TIP", text: "If your mix sounds thin, check for a 'phase' issue between your two overhead drum mics." },
    { type: "HISTORY", text: "The 'Moog' synthesizer was the first to use a keyboard to control electronic sounds." },
    { type: "FACT", text: "The 'Whole Tone' scale consists entirely of intervals of a major second." },
    { type: "PSYCHOLOGY", text: "Music can improve the quality of life for people with dementia by reducing agitation." },
    { type: "BIOLOGY", text: "High decibel levels cause the 'acoustic reflex,' where the middle ear pulls back to protect itself." },
    { type: "TIP", text: "When EQing, try a 'wide' Q for boosts and a 'narrow' Q for cutting problematic frequencies." },
    { type: "HISTORY", text: "The 'Theremin' was invented by a Soviet physicist while he was researching proximity sensors." },
    { type: "FACT", text: "The violin, viola, and cello are all members of the 'String' family of instruments." },
    { type: "PSYCHOLOGY", text: "Listening to sad music when you are already sad can actually provide emotional catharsis." },
    { type: "BIOLOGY", text: "The pinna (outer ear) is shaped specifically to funnel sound waves into the ear canal." },
    { type: "TIP", text: "Record your room's 'ambient noise' for 30 seconds to help with seamless audio editing later." },
    { type: "HISTORY", text: "The term 'Heavy Metal' was first used in a musical context in the song 'Born to be Wild'." },
    { type: "FACT", text: "The 'Circle of Fifths' is a visual representation of the relationships between the 12 tones." },
    { type: "PSYCHOLOGY", text: "People who play instruments are often better at 'multitasking' than those who don't." },
    { type: "BIOLOGY", text: "The speed of sound is affected by temperature; sound travels faster in warm air." },
    { type: "TIP", text: "If your kick drum is getting lost, carve out a small hole in the bass guitar EQ at the same frequency." },
    { type: "HISTORY", text: "The 1970s disco era began in private underground dance clubs in New York City." },
    { type: "FACT", text: "A 'Capo' is a device used on the neck of a stringed instrument to shorten the playable length." },
    { type: "PSYCHOLOGY", text: "The 'Earworm' is most likely to be a song with a simple, repetitive melody." },
    { type: "BIOLOGY", text: "Loud music can cause the release of adrenaline, which is why it feels 'energizing'." },
    { type: "TIP", text: "Use a 'Gate' on drum mics to prevent the sound of other drums from 'bleeding' into the channel." },
    { type: "HISTORY", text: "The first opera ever written was 'Dafne' by Jacopo Peri in 1597." },
    { type: "FACT", text: "A 'Semi-quaver' is the British term for a sixteenth note." },
    { type: "PSYCHOLOGY", text: "Music can influence how we perceive the taste of food and wine." },
    { type: "BIOLOGY", text: "The auditory nerve contains approximately 30,000 individual nerve fibers." },
    { type: "TIP", text: "To make a vocal sound 'intimate,' use a condenser microphone very close to the singer." },
    { type: "HISTORY", text: "The 'Grunge' movement originated in Seattle in the mid-1980s." },
    { type: "FACT", text: "The 'Nut' of a guitar is the small strip of material at the end of the fretboard." },
    { type: "PSYCHOLOGY", text: "Singing in the shower is common because the hard surfaces create pleasing natural reverb." },
    { type: "BIOLOGY", text: "Excessive earwax can cause 'conductive' hearing loss by blocking sound waves." },
    { type: "TIP", text: "Always record your DI (Direct Input) guitar signal, even if you are using a real amp." },
    { type: "HISTORY", text: "The 'Harpsichord' was the primary keyboard instrument before the invention of the piano." },
    { type: "FACT", text: "A 'Major' chord is built with a root, a major third, and a perfect fifth." },
    { type: "PSYCHOLOGY", text: "The 'Binaural Beat' phenomenon occurs when two different frequencies are played in each ear." },
    { type: "BIOLOGY", text: "Permanent hearing loss can occur after just one exposure to an extremely loud 'impulse' sound." },
    { type: "TIP", text: "When mixing high-hats, use a high-pass filter to remove any unnecessary low-end rumble." },
    { type: "HISTORY", text: "The 'Jazz Age' is a term coined by F. Scott Fitzgerald to describe the 1920s." },
    { type: "FACT", text: "The 'Glockenspiel' is a percussion instrument consisting of tuned metal bars." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
    { type: "PSYCHOLOGY", text: "Music can help athletes 'get in the zone' by blocking out external distractions." },
    { type: "BIOLOGY", text: "The human ear is fully formed at birth and does not grow significantly larger with age." },
    { type: "TIP", text: "Check your levels! Avoid 'clipping' in the digital domain, as it creates harsh distortion." },
];

export const CHAOS_QUERIES = [
    'official audio greatest hits',
    'legendary songs official audio',
    'classic pop hits official',
    'rock classics official audio',
    'soul classics official',
    'jazz standards official audio',
    'bollywood classics official audio',
    'international pop hits official'
];

export const GENERIC_CHAOS_QUERIES = [
    'greatest hits', 'top songs', 'classic hits',
    'pop anthems', '80s hits', '90s classics',
    '2000s hits', 'jazz classics', 'lofi beats',
    'rock anthems', 'soul classics', 'famous songs',
    'viral hits', 'party songs', 'love songs',
    'golden oldies', 'legendary songs', 'chart toppers'
];

export const MOOD_DATA: Record<
    string,
    { queries: string[]; icon: any; description: string }
> = {
    Happy: {
        queries: ['feel good songs official audio', 'upbeat pop official'],
        icon: Smile,
        description: 'light, warm, smiling inside',
    },
    Chill: {
        queries: ['chill acoustic official audio', 'soft relaxing music official'],
        icon: Coffee,
        description: 'nothing loud, nothing urgent',
    },
    Romantic: {
        queries: ['romantic ballads official audio', 'love songs official'],
        icon: Heart,
        description: 'soft thoughts, closer feelings',
    },
    Energy: {
        queries: ['workout motivation official audio', 'high energy songs official'],
        icon: Zap,
        description: 'move, don’t overthink',
    },
    Melancholy: {
        queries: ['sad emotional songs official', 'melancholic music official'],
        icon: CloudRain,
        description: 'not broken, just quiet',
    },
    Focus: {
        queries: ['instrumental focus music', 'ambient study music'],
        icon: BookOpen,
        description: 'thoughts aligned',
    },
    World: {
        queries: ['world music official audio', 'international hits official'],
        icon: Globe,
        description: 'far places, familiar feelings',
    },
    Retro: {
        queries: ['90s hits official audio', '2000s songs official'],
        icon: Disc,
        description: 'memories, softly replaying',
    }
};

export const MOODS = Object.keys(MOOD_DATA);
export const LANGUAGES = ['Any', 'English', 'Spanish', 'Korean', 'Hindi', 'Japanese', 'Egyptian', 'Arabic', 'Urdu', 'Hausa', 'Punjabi', 'Tamil', 'Telugu', 'Malayalam', 'Kannada', 'Bengali', 'Marathi', 'Gujarati', 'Oriya', 'Assamese', 'Sinhala', 'Bhojpuri', 'Kashmiri', 'Konkani', 'Nepali', 'Sanskrit'];
